### ISSUE TITLE
Support for Magento 2.1

### ISSUE THREAD

**Issue by ThailandCat** [omise/omise-magento#29]
Will be happy to see Magento 2.1 version of this plugin.

**Comment by dmitry-fedyuk** [comment]
I have created a Magento 2 extension for Omise: https://mage2.pro/c/extensions/omise
It works with all the Magento 2 versions (including 2.1), and will do so ever because I support it and test it with coming releases.
## Screenshots

### 1. Magento frontend checkout

The extension keeps the bank cards details, and the customer can use them for the next payments with just a click.
The bank cards details are stored on the Omise server, so your store does not need to be PCI DSS certified.

![magento2-omise-payment-02](https://cloud.githubusercontent.com/assets/83204/20403789/3b0277e8-ad13-11e6-8582-768eb5a96607.png)

### 2. Magento backend settings
![magento2-omise-payment-settings](https://cloud.githubusercontent.com/assets/83204/20403803/43305782-ad13-11e6-9e5c-661b9a11f8fa.png)

### 3. Payment information block on a Magento backend order screen
![31f63502e3ace8ef8e8adab1851caad26b5702f4 1](https://cloud.githubusercontent.com/assets/83204/20403826/5e488968-ad13-11e6-80f8-b087fd80e351.png)

### 4. Magento backend's transation data screen
![02](https://cloud.githubusercontent.com/assets/83204/20403846/75dea418-ad13-11e6-9f66-4a482d3e418d.png)

### 5. Magento backend's transation details screen
![03](https://cloud.githubusercontent.com/assets/83204/20403852/7aed3816-ad13-11e6-897f-18d0bf282522.png)

**Comment by ThailandCat** [comment]
Thank you, $250+ for payment plugin is not a price which Thailand market was expected

Сделайте 30 долларов и я первый куплю, не дожидаясь пока эти тормоза выпустят что-то. Самому писать тупо времени нет...

**Comment by guzzilar** [comment]
@ThailandCat Hi, sorry that it seems a bit late to inform, but we already provided plugin for Magento CE 2.x series. 

You can check it here, https://github.com/omise/omise-magento.

Cheers,
Nam.
